# psp-role       | predefined ? -> scf default account
# configgin-role | predefined ? -> scf default account

# Service account, roles, and cluster role for the brain tests.
# Raw kube objects going into the chart.
# TODO: Make this conditional.

# Service account "tests-brain" is used by the instance group "acceptance-tests-brain"
---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: "{{ .Values.deployment_name }}-tests-brain"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: "{{ .Values.deployment_name }}-tests-brain"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ include "kubecf.fullname" . }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ include "kubecf.chart" . }}

# Role "test-role-brain" only used by account "tests-brain"
# The permissions are a combination of the SCF roles
# configgin-role, psp-role, and test-brain-role.
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "Role"
metadata:
  name: "{{ .Values.deployment_name }}-test-role-brain"
  labels:
    app.kubernetes.io/component: "{{ .Values.deployment_name }}-test-role-brain"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ include "kubecf.fullname" . }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ include "kubecf.chart" . }}
rules:
- apiGroups:
  - ""
  resources:
  - "services"
  verbs:
  - "create"
  - "get"
  - "delete"
  - "list"
  - "patch"
- apiGroups:
  - "extensions"
  resourceNames:
  - "default"
  resources:
  - "podsecuritypolicies"
  verbs:
  - "use"
- apiGroups:
  - "extensions"
  resources:
  - "replicasets"
  verbs:
  - "create"
  - "get"
  - "list"
  - "delete"
  - "update"
- apiGroups:
  - "apps"
  resources:
  - "statefulsets"
  verbs:
  - "create"
  - "get"
  - "update"
  - "delete"
  - "list"
  - "patch"
- apiGroups:
  - ""
  resources:
  - "pods"
  verbs:
  - "create"
  - "get"
  - "list"
  - "delete"
  - "update"
  - "patch"
- apiGroups:
  - ""
  resources:
  - "pods/exec"
  verbs:
  - "create"
  - "delete"
- apiGroups:
  - ""
  resources:
  - "pods/log"
  verbs:
  - "create"
  - "delete"
  - "get"
  - "list"
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs:
  - "create"
  - "get"
  - "delete"
  - "list"

# Role binding for service account "tests-brain" and role "test-role-brain"
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "RoleBinding"
metadata:
  name: "{{ .Values.deployment_name }}-tests-brain-test-role-brain-binding"
  labels:
    app.kubernetes.io/component: "{{ .Values.deployment_name }}-tests-brain-test-role-brain-binding"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ include "kubecf.fullname" . }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ include "kubecf.chart" . }}
subjects:
- kind: "ServiceAccount"
  name: "{{ .Values.deployment_name }}-tests-brain"
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "Role"
  name: "{{ .Values.deployment_name }}-test-role-brain"

# Cluster role "test-cluster-role" only used by account "tests-brain"
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRole"
metadata:
  name: "{{ .Release.Namespace }}-{{ .Values.deployment_name }}-test-cluster-role"
  labels:
    app.kubernetes.io/component: "{{ .Release.Namespace }}-{{ .Values.deployment_name }}-test-cluster-role"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ include "kubecf.fullname" . }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ include "kubecf.chart" . }}
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  verbs:
  - "create"
  - "get"
  - "delete"
- apiGroups:
  - ""
  resources:
  - "pods"
  - "pods/log"
  - "namespaces"
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - ""
  resources:
  - "pods/portforward"
  verbs:
  - "create"
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "clusterrolebindings"
  verbs:
  - "delete"
- apiGroups:
  - ""
  resources:
  - "persistentvolumes"
  - "persistentvolumeclaims"
  verbs:
  - "get"
  - "list"
- apiGroups:
  - "storage.k8s.io"
  resources:
  - "storageclasses"
  verbs:
  - "get"
  - "list"
- apiGroups:
  - "batch"
  resources:
  - "jobs"
  verbs:
  - "get"
  - "list"

# Cluster role binding for service account "tests-brain" and cluster role "test-cluster-role"
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRoleBinding"
metadata:
  name: "{{ .Release.Namespace }}-{{ .Values.deployment_name }}-tests-brain-test-cluster-role-cluster-binding"
  labels:
    app.kubernetes.io/component: "{{ .Release.Namespace }}-{{ .Values.deployment_name }}-tests-brain-test-cluster-role-cluster-binding"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ include "kubecf.fullname" . }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ include "kubecf.chart" . }}
subjects:
- kind: "ServiceAccount"
  name: "{{ .Values.deployment_name }}-tests-brain"
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: "ClusterRole"
  apiGroup: "rbac.authorization.k8s.io"
  name: "{{ .Release.Namespace }}-{{ .Values.deployment_name }}-test-cluster-role"
